# NOTE(Jack): Currently there are no other sub options except for circle grid! For april grid3 the tag family is at
# this time hardcoded but in future we could add another section like april_grid3_options. It should be clear to the
# that these options are only read when the target.type matches the options.

target:
  type: "circle_grid" # checkerboard, circle_grid, april_grid3
  pattern_size: [ 6,7 ] # [row, column]
  unit_dimension: 0.05 # (m) different measurement for each target
  circle_grid_options:
    asymmetric: true
